spring:
  profiles:
    active: development
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8080

#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  datasource:
#    tomcat: # Keep the connection alive if idle for a long time (needed in production) https://stackoverflow.com/questions/22684807/spring-boot-jpa-configuring-auto-reconnect
#      test-while-idle: true
#      validation-query: SELECT 1
#  profiles:
#    active: prodlike
#
#    # ===============================
#    # = JPA / HIBERNATE
#    # ===============================
#  jpa:
#    show-sql: false   # Show or not log for each sql query
#    hibernate:
#      ddl-auto: none  # Hibernate ddl auto (create, create-drop, update): with "create-drop" the database schema will be automatically created afresh for every start of application
#      naming:         # Naming strategy
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#
#  properties:
#    hibernate:
#      dialect: org.hibernate.dialect.Oracle10gDialect # Allows Hibernate to generate SQL optimized for a particular DBMS
