# ===============================
# = DATA SOURCE
# ===============================
# Set here configurations for the database connection

#datasource:
#
#  crm:
#    jdbcUrl: "jdbc:oracle:thin:@xxx"
#    username: ${db.usr}
#    password: ${db.pwd}
#    testWhileIdle: true
#    validationQuery: SELECT 1 from dual
#    testOnBorrow: true


server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
